ffmpeg:
  path: /opt/homebrew/bin/ffmpeg

logging:
  config: config/log4j2.xml
  file:
    name: ../log/google-speech.log

server:
  port: 8800
  
asterisk:
  agi:
    host: 127.0.0.1
    port: 9000
    poolSize: 500
    maximumPoolSize: 3000
  ami:
    host: 127.0.0.1
    username: <replace it with your own virtual machine Manager Username>
    password: <replace it with your own virtual machine Manager Password>

originate:
  originateTrunk: piecebyte
  originateContext: OUTBOUND_DIALER
  originateExtension: s

audio:
  path: /var/lib/asterisk/sounds/en

google:
  credentials:
    file:
      path: /home/ubuntu/google-auth.json
  gemini:
    geminiApiUrl: "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key="
    geminiApiKey: "REPLACE WITH YOUR OWN GEMINI API KEY"
